CREATE VIEW CONGRESDETAILVIEW AS
SELECT C.*,
		D.IDDETAILCONGRES,D.DESIGNATION,D.MONTANT
FROM CONGRES C
JOIN DETAILCONGRES D
ON C.IDCONGRES = D.IDCONGRES


CREATE VIEW SOMMEPAYECOTISATION AS
SELECT M.*,
		C.*,
      SUM(P.MONTANT) AS MONTANTPAYE
FROM MEMBRE M
JOIN PAIEMENTCOTISATION P
ON M.IDMEMBRE = P.IDMEMBRE
JOIN COTISATION C
ON P.IDCOTISATION = C.IDCOTISATION
GROUP BY C.IDCOTISATION, M.IDMEMBRE

CREATE VIEW SOMMEPAYECONGRES AS
SELECT M.*,
		C.IDCONGRES, C.NOMCONGRES, C.IDDETAILCONGRES,C.DESIGNATION, C.MONTANT,
      SUM(P.MONTANT) AS MONTANTPAYE
FROM MEMBRE M
JOIN PAIEMENTCONGRES P
ON M.IDMEMBRE = P.IDMEMBRE
JOIN CONGRESDETAILVIEW C
ON P.IDDETAILCONGRES = C.IDDETAILCONGRES
GROUP BY C.IDCONGRES,C.NOMCONGRES,C.IDDETAILCONGRES, C.DESIGNATION, C.MONTANT, M.IDMEMBRE

CREATE VIEW DETAILPAIEMENTCOTISATION AS
SELECT M.*,
		C.*,
		P.IDPAIEMENTCOTISATION,P.DATEPAIEMENT,P.MONTANT AS MONTANTPAYE
FROM MEMBRE M
JOIN PAIEMENTCOTISATION P
ON M.IDMEMBRE = P.IDMEMBRE
JOIN COTISATION C
ON P.IDCOTISATION = C.IDCOTISATION

CREATE VIEW DETAILPAIEMENTCONGRES AS
SELECT M.*,
		C.IDCONGRES, C.NOMCONGRES, C.IDDETAILCONGRES,C.DESIGNATION, C.MONTANT,
      P.IDPAIEMENTCONGRES,P.DATEPAIEMENT,P.MONTANT AS MONTANTPAYE
FROM MEMBRE M
JOIN PAIEMENTCONGRES P
ON M.IDMEMBRE = P.IDMEMBRE
JOIN CONGRESDETAILVIEW C
ON P.IDDETAILCONGRES = C.IDDETAILCONGRES

CREATE VIEW LISTCOTISATION AS
SELECT COUNT(M.IDMEMBRE) AS CONTRIBUABLE,
		C.*,
		SUM(P.MONTANT) AS MONTANTPAYE
FROM COTISATION C
LEFT JOIN PAIEMENTCOTISATION P
ON P.IDCOTISATION = C.IDCOTISATION
LEFT JOIN MEMBRE M
ON M.IDMEMBRE = P.IDMEMBRE
GROUP BY C.ANNEECOTISATION, C.MONTANTOBJECTIF, C.IDCOTISATION

SELECT IDMEMBRE,IDCOTISATION,SUM(MONTANT),extract(year from DATEPAIEMENT)  
FROM PAIEMENTCOTISATION 
GROUP BY IDCOTISATION, IDMEMBRE, extract(year from DATEPAIEMENT)